version: '3.8'

services:

  user-profile-service:
    image: user-profile-service
    build:
      dockerfile: Dockerfile
    container_name: user-profile-service
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres:14.10
    environment:
      POSTGRES_DB: "user_profile"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
    depends_on:
      - postgres