version: '3.8'

networks:
  user-profile-network:
    driver: bridge

services:

  user-profile-service:
    #    restart: unless-stopped
    image: user-profile-service:latest
    build:
      context: .
      dockerfile: user-profile/Dockerfile
    container_name: user-profile-service
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - user-profile-network

  postgres:
    container_name: postgres
    image: postgres:14.10
    environment:
      POSTGRES_DB: "user_profile"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432"
    networks:
      - user-profile-network

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
    depends_on:
      - postgres
    networks:
      - user-profile-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin