global:
  scrape_interval:     5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'user-profile-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8080']