name: Build

on:
  push:
    branches:       
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew build
    - name: Run Tests
      run: ./gradlew test
